#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 404299862                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://healthi.net                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : healthi                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : COMING SOON

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

app_logo                                  : assets/logo.png



# Information About Yourself
your_name                                 : Sunshine Health Studios                                
your_link                                 : https://healthi.net
your_city                                 :
email_address                             : hello@healthi.net
facebook_username                         :                                    
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Choose Your Plan
    description                           : With some information from you, Healthi will recommend a personalized weight loss plan that’s been proven to show results based on your goals and your body type.
    fontawesome_icon_name                 : magic
    
  - title                                 : Track Your Food
    description                           : Users that track foods for 7 consecutive days are more likely to lose weight than those who don’t. We hold you accountable so you can achieve your best results
    fontawesome_icon_name                 : mobile

  - title                                 : Lose Your Weight
    description                           : With consistent tracking, support from the Healthi community and tasty recipes, you can join the millions of success stories and achieve your weight loss goals.
    fontawesome_icon_name                 : play-circle

# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 0.1
topbar_title_color                        : "#444444"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#C6DF89"

app_title_color                           : "#555555"
app_price_color                           : "#555555"
app_description_color                     : "#666666"

feature_title_color                       : "#444444"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ABD7E9"
feature_icons_background_color            : "#F9F9F9"

social_icons_foreground_color             : "#ABD7E9"
social_icons_background_color             : "#F9F9F9"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
